Increase the duration of the high error rate polices
netuitive-community-packages/netuitive-packages-aws-alb pull request #13
Opened 2018-11-12 21:37 UTC by TheConnMan

Single cycle elevated error rates are not indicative of widespread errors and cause too much noise.

2018-11-12 21:56 UTC, rclagett commented on README.md
> +* Increase the duration of the high error rate polices
`### Version next` is missing

2018-11-12 23:40 UTC, Grumblesmith requested changes

2018-11-12 23:40 UTC, Grumblesmith commented on README.md
> +* Increase the duration of the high error rate polices
```suggestion
### Version next

* Increase the duration of the high error rate polices
```

2018-11-13 17:09 UTC, rclagett approved these changes

2018-11-13 17:21 UTC, Grumblesmith approved these changes

2018-11-14 14:34 UTC, merged