Improvement/updated policies sudden change
netuitive-community-packages/netuitive-packages-aws-alb pull request #8
Opened 2018-07-27 18:22 UTC by jemassey

2018-07-27 18:27 UTC, TheConnMan requested changes

2018-07-27 18:27 UTC, TheConnMan commented on README.md
> +### Version 1.3.1
The version is only added when dev is cut over to master.

2018-07-27 18:27 UTC, TheConnMan commented on package.json
> +  "version": "1.3.1",
Same as in the readme.

2018-07-27 18:27 UTC, TheConnMan commented on policies/decreased_load_balancer_error_rate.json
> +        "id": 54829,
These are internal IDs. Please remove them.

2018-07-27 18:27 UTC, TheConnMan commented on policies/decreased_load_balancer_error_rate.json
> +    "id": "4ccd5f3f-f42e-3f8b-a1ef-7921639cd97d",
IDs and last updated should be removed.

2018-07-27 18:27 UTC, TheConnMan commented on policies/decreased_request_count.json
> +        "id": 54829,
See above.

2018-07-27 18:27 UTC, TheConnMan commented on policies/decreased_target_response_time.json
> +        "id": 54829,
See above.

2018-07-27 18:27 UTC, TheConnMan commented on policies/increased_load_balancer_error_rate.json
> +        "id": 54829,
See above.

2018-07-27 18:27 UTC, TheConnMan commented on policies/increased_request_count.json
> +        "id": 54829,
See above.

2018-07-27 18:27 UTC, TheConnMan commented on policies/increased_target_response_time.json
> +        "id": 54829,
See above.

2018-07-27 18:53 UTC, TheConnMan approved these changes

2018-08-03 02:00 UTC, Grumblesmith approved these changes

2018-08-03 13:03 UTC, TheConnMan requested changes

2018-08-03 13:03 UTC, TheConnMan commented on package.json
> +  "version": "1.4.0",
The version should not be updated in PRs.

2018-08-03 16:31 UTC, TheConnMan approved these changes

2018-08-03 17:53 UTC, merged